import { useEffect, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import {
  useListUsers,
  useUpdateUser,
  useDeleteUser,
  useGetMe,
  createUser,
  getListUsersQueryKey,
} from "@workspace/api-client-react";
import {
  initializeApp,
  deleteApp,
  type FirebaseApp,
} from "firebase/app";
import {
  getAuth,
  createUserWithEmailAndPassword,
} from "firebase/auth";
import { firebaseConfig } from "@/lib/firebase";
import {
  Users as UsersIcon,
  Plus,
  Search,
  Mail,
  Phone,
  Shield,
  Power,
  UserRound,
  CircleCheck,
  CircleOff,
  X,
  Copy,
  Check,
  Loader2,
  Trash2,
  AlertTriangle,
} from "lucide-react";
import { format } from "date-fns";
import { useToast } from "@/hooks/use-toast";
import { EmptyTableState, PaginationBar, TableSkeleton } from "@/components/table-state";

type Role = "admin" | "sales" | "finance" | "warehouse" | "engineer";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function generateTempPassword(): string {
  const lower = "abcdefghjkmnpqrstuvwxyz";
  const upper = "ABCDEFGHJKLMNPQRSTUVWXYZ";
  const digits = "23456789";
  const special = "!@#$";
  const pick = (s: string) => s[Math.floor(Math.random() * s.length)];

  const parts = [
    pick(upper), pick(upper),
    pick(lower), pick(lower), pick(lower), pick(lower),
    pick(digits), pick(digits),
    pick(special),
  ];

  // Fisher-Yates shuffle
  for (let i = parts.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [parts[i], parts[j]] = [parts[j], parts[i]];
  }

  return parts.join("");
}

// ─── Create User Modal ────────────────────────────────────────────────────────

interface CreateForm {
  name: string;
  email: string;
  role: Role;
  phone: string;
  password: string;
}

function CreateUserModal({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: () => void;
}) {
  const { toast } = useToast();

  const [form, setForm] = useState<CreateForm>({
    name: "",
    email: "",
    role: "sales",
    phone: "",
    password: "",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  // When set, show the "success + copy password" screen
  const [createdPassword, setCreatedPassword] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const set =
    (field: keyof CreateForm) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
      setForm((f) => ({ ...f, [field]: e.target.value }));

  const handleCopy = () => {
    if (!createdPassword) return;
    navigator.clipboard.writeText(createdPassword).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleSubmit = async () => {
    if (!form.name.trim() || !form.email.trim()) return;

    setIsSubmitting(true);

    const finalPassword = form.password.trim() || generateTempPassword();
    const wasAutoGenerated = !form.password.trim();

    // Use a uniquely-named secondary app so this createUserWithEmailAndPassword
    // call does NOT sign in / sign out the admin's primary Firebase session.
    let tempApp: FirebaseApp | null = null;

    try {
      tempApp = initializeApp(firebaseConfig, `create-user-${Date.now()}`);
      const tempAuth = getAuth(tempApp);

      // Step 1 — Create Firebase Auth account
      const cred = await createUserWithEmailAndPassword(
        tempAuth,
        form.email.trim().toLowerCase(),
        finalPassword
      );

      const firebaseUid = cred.user.uid;

      // Step 2 — Create DB record
      try {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await createUser({
          name: form.name.trim(),
          email: form.email.trim().toLowerCase(),
          role: form.role,
          phone: form.phone.trim() || undefined,
          // firebaseUid is not in the generated UserInput type but the route
          // accepts and stores any extra body fields.
          firebaseUid,
        } as any);
      } catch (dbErr) {
        // DB failed → roll back the Firebase account before surfacing the error
        await cred.user.delete();
        throw dbErr;
      }

      // Both succeeded
      onCreated();
      toast({ title: "User created successfully" });

      // Show the generated password only if it was auto-generated
      if (wasAutoGenerated) {
        setCreatedPassword(finalPassword);
      } else {
        onClose();
      }
    } catch (err: unknown) {
      const msg =
        err instanceof Error ? err.message : "An unexpected error occurred";
      toast({ title: "Failed to create user", description: msg, variant: "destructive" });
    } finally {
      if (tempApp) {
        // Clean up secondary app — fire-and-forget; errors here are harmless
        deleteApp(tempApp).catch(() => {});
      }
      setIsSubmitting(false);
    }
  };

  // ── Success screen ──────────────────────────────────────────────────────────
  if (createdPassword) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm sm:p-6">
        <div className="my-auto w-full max-w-md overflow-hidden rounded-2xl border border-white/70 bg-white shadow-2xl shadow-slate-950/20">
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-600">Access ready</p>
              <h2 className="mt-1 font-heading text-xl font-bold tracking-tight text-slate-900">User created</h2>
            </div>
            <button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30">
              <X className="h-4 w-4" />
            </button>
          </div>
          <div className="space-y-5 p-5 sm:p-6">
            <div className="flex items-start gap-3 rounded-xl border border-emerald-100 bg-emerald-50/70 p-3.5">
              <CircleCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600" />
              <p className="text-sm leading-6 text-emerald-900">
                The account for <span className="font-semibold">{form.email}</span> has been created successfully.
              </p>
            </div>
            <p className="text-sm leading-6 text-slate-600">
              Share the temporary password securely with the new team member. It will not be shown again after closing this dialog.
            </p>
            <div>
              <p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">
                Temporary password
              </p>
              <div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-3">
                <code className="flex-1 select-all font-mono text-sm tracking-wider text-slate-900">
                  {createdPassword}
                </code>
                <button
                  type="button"
                  onClick={handleCopy}
                  className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 text-xs font-semibold text-slate-600 shadow-sm transition-colors hover:border-primary/30 hover:bg-primary/5 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30"
                  title="Copy temporary password"
                  aria-label="Copy temporary password"
                >
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 text-emerald-600" />
                      <span>Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>
              <p className="mt-2 text-xs leading-5 text-amber-700">Save this password now. It won't be shown again.</p>
            </div>
          </div>
          <div className="border-t border-slate-100 p-5 sm:px-6">
            <button
              type="button"
              onClick={onClose}
              className="h-10 w-full rounded-lg bg-primary text-sm font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Create form ─────────────────────────────────────────────────────────────
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm sm:p-6">
      <div className="my-auto max-h-[calc(100dvh-2rem)] w-full max-w-lg overflow-y-auto rounded-2xl border border-white/70 bg-white shadow-2xl shadow-slate-950/20">
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur sm:px-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Team access</p>
            <h2 className="mt-1 font-heading text-xl font-bold tracking-tight text-slate-900">Add new user</h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            disabled={isSubmitting}
            className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:opacity-50"
            aria-label="Close add user dialog"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="space-y-5 p-5 sm:p-6">
          <div className="flex items-start gap-3 rounded-xl border border-primary/15 bg-primary/[0.06] p-3.5">
            <UserRound className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
            <p className="text-sm leading-6 text-slate-600">Create a team account and assign the access level they need to work in the CRM.</p>
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Full name <span className="text-red-500">*</span>
            </label>
            <input
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.name}
              onChange={set("name")}
              placeholder="Full name"
              disabled={isSubmitting}
            />
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Email <span className="text-red-500">*</span>
            </label>
            <input
              type="email"
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.email}
              onChange={set("email")}
              placeholder="user@sunpower.com"
              disabled={isSubmitting}
            />
          </div>

          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <div>
              <label className="mb-1.5 block text-sm font-semibold text-slate-800">
                Role
              </label>
              <select
                className="h-11 w-full rounded-lg border border-input bg-white px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
                value={form.role}
                onChange={set("role")}
                disabled={isSubmitting}
              >
                <option value="admin">Admin</option>
                <option value="sales">Sales</option>
                <option value="finance">Finance</option>
                <option value="warehouse">Warehouse</option>
                <option value="engineer">Engineer</option>
              </select>
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-semibold text-slate-800">
                Phone{" "}
                <span className="text-gray-400 font-normal">(optional)</span>
              </label>
              <input
                className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
                value={form.phone}
                onChange={set("phone")}
                placeholder="+91 XXXXX XXXXX"
                disabled={isSubmitting}
              />
            </div>
          </div>

          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Password{" "}
              <span className="text-gray-400 font-normal">
                (leave blank to auto-generate)
              </span>
            </label>
            <input
              type="password"
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.password}
              onChange={set("password")}
              placeholder="Auto-generated if left blank"
              disabled={isSubmitting}
            />
          </div>
        </div>

        <div className="sticky bottom-0 flex flex-col-reverse gap-2.5 border-t border-slate-100 bg-white/95 p-5 backdrop-blur sm:flex-row sm:justify-end sm:px-6">
          <button
            type="button"
            onClick={onClose}
            disabled={isSubmitting}
            className="h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:opacity-50 sm:min-w-28"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={isSubmitting || !form.name.trim() || !form.email.trim()}
            onClick={handleSubmit}
            className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:opacity-50 sm:min-w-36"
          >
            {isSubmitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Creating…
              </>
            ) : (
              "Create User"
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Edit User Modal ──────────────────────────────────────────────────────────

interface EditForm {
  name: string;
  email: string;
  role: Role;
  phone: string;
  isActive: string;
  password: string;
}

function EditUserModal({
  userId,
  initial,
  onClose,
  onSubmit,
  isPending,
}: {
  userId: number;
  initial: EditForm;
  onClose: () => void;
  onSubmit: (data: EditForm) => void;
  isPending: boolean;
}) {
  const [form, setForm] = useState<EditForm>(initial);
  const set =
    (field: keyof EditForm) =>
    (
      e: React.ChangeEvent<
        HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
      >
    ) => setForm((f) => ({ ...f, [field]: e.target.value }));

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm sm:p-6">
      <div className="my-auto max-h-[calc(100dvh-2rem)] w-full max-w-lg overflow-y-auto rounded-2xl border border-white/70 bg-white shadow-2xl shadow-slate-950/20">
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur sm:px-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Team access</p>
            <h2 className="mt-1 font-heading text-xl font-bold tracking-tight text-slate-900">
              Edit user
            </h2>
          </div>
          <button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30" aria-label="Close edit user dialog">
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="space-y-5 p-5 sm:p-6">
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Full name
            </label>
            <input
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.name}
              onChange={set("name")}
              placeholder="Full name"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Email
            </label>
            <input
              type="email"
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.email}
              onChange={set("email")}
              placeholder="email@example.com"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Role
            </label>
            <select
              className="h-11 w-full rounded-lg border border-input bg-white px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.role}
              onChange={set("role")}
            >
              <option value="admin">Admin</option>
              <option value="sales">Sales</option>
              <option value="finance">Finance</option>
              <option value="warehouse">Warehouse</option>
              <option value="engineer">Engineer</option>
            </select>
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Phone{" "}
              <span className="text-gray-400 font-normal">(optional)</span>
            </label>
            <input
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.phone}
              onChange={set("phone")}
              placeholder="+91 XXXXX XXXXX"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              Status
            </label>
            <select
              className="h-11 w-full rounded-lg border border-input bg-white px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.isActive}
              onChange={set("isActive")}
            >
              <option value="true">Active</option>
              <option value="false">Inactive</option>
            </select>
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-800">
              New Password{" "}
              <span className="text-gray-400 font-normal">
                (leave blank to keep unchanged)
              </span>
            </label>
            <input
              type="password"
              className="h-11 w-full rounded-lg border border-input px-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25"
              value={form.password}
              onChange={set("password")}
              placeholder="New password"
            />
          </div>
        </div>

        <div className="sticky bottom-0 flex flex-col-reverse gap-2.5 border-t border-slate-100 bg-white/95 p-5 backdrop-blur sm:flex-row sm:justify-end sm:px-6">
          <button
            type="button"
            onClick={onClose}
            className="h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 sm:min-w-28"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={isPending || !form.name || !form.email}
            onClick={() => onSubmit(form)}
            className="inline-flex h-10 items-center justify-center rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:opacity-50 sm:min-w-36"
          >
            {isPending ? "Saving..." : "Save Changes"}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Delete Confirm Dialog ────────────────────────────────────────────────────

function DeleteConfirmDialog({
  user,
  onClose,
  onConfirm,
  isPending,
}: {
  user: { id: number; name: string; email: string; role: string };
  onClose: () => void;
  onConfirm: () => void;
  isPending: boolean;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm">
      <div className="w-full max-w-md overflow-hidden rounded-2xl border border-white/70 bg-white shadow-2xl shadow-slate-950/20">
        <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-red-600">Irreversible action</p>
            <h2 className="mt-1 font-heading text-xl font-bold tracking-tight text-slate-900">Delete user</h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            disabled={isPending}
            className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:opacity-50"
            aria-label="Close delete user dialog"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="space-y-4 p-5 sm:p-6">
          <div className="flex items-start gap-3 rounded-xl border border-red-100 bg-red-50/70 p-3.5">
            <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-red-600" />
            <div>
              <p className="text-sm leading-6 text-slate-700">
                Are you sure you want to delete{" "}
                <span className="font-semibold text-slate-900">{user.name}</span>?
              </p>
              <p className="mt-1 text-xs text-slate-500">{user.email}</p>
            </div>
          </div>
          <p className="rounded-lg border border-red-100 bg-red-50 px-3 py-2.5 text-sm leading-6 text-red-700">
            This permanently removes their account and revokes all access. This action cannot be undone.
          </p>
        </div>

        <div className="flex flex-col-reverse gap-2.5 border-t border-slate-100 p-5 sm:flex-row sm:justify-end sm:px-6">
          <button
            type="button"
            onClick={onClose}
            disabled={isPending}
            className="h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold text-slate-700 transition-colors hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:opacity-50 sm:min-w-28"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={onConfirm}
            disabled={isPending}
            className="flex h-10 items-center justify-center gap-2 rounded-lg bg-red-600 px-4 text-sm font-semibold text-white transition-colors hover:bg-red-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-300 disabled:opacity-50 sm:min-w-36"
          >
            {isPending ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Deleting…
              </>
            ) : (
              "Delete User"
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export function Users() {
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState<string>("");
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [editTarget, setEditTarget] = useState<number | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<{
    id: number; name: string; email: string; role: string;
  } | null>(null);
  const [togglingIds, setTogglingIds] = useState<Set<number>>(new Set());
  const [page, setPage] = useState(1);
  const pageSize = 8;

  const queryClient = useQueryClient();
  const { toast } = useToast();

  const { data: currentUser } = useGetMe();

  const { data: users, isLoading } = useListUsers({
    search: search || undefined,
    role: roleFilter || undefined,
  });
  const pageCount = Math.max(1, Math.ceil((users?.length ?? 0) / pageSize));
  const visibleUsers = users?.slice((page - 1) * pageSize, page * pageSize) ?? [];

  useEffect(() => {
    setPage(1);
  }, [search, roleFilter]);

  useEffect(() => {
    if (page > pageCount) setPage(pageCount);
  }, [page, pageCount]);

  const updateUser = useUpdateUser({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListUsersQueryKey() });
        setEditTarget(null);
        toast({ title: "User updated successfully" });
      },
      onError: () => {
        toast({ title: "Failed to update user", variant: "destructive" });
      },
    },
  });

  const deleteUser = useDeleteUser({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListUsersQueryKey() });
        setDeleteTarget(null);
        toast({ title: "User deleted successfully" });
      },
      onError: (err: unknown) => {
        // Surface the server's guard message (403) or a generic fallback
        const msg =
          err instanceof Error ? err.message : "An unexpected error occurred";
        toast({ title: "Failed to delete user", description: msg, variant: "destructive" });
        setDeleteTarget(null);
      },
    },
  });

  const editTargetUser = users?.find((u) => u.id === editTarget);

  const handleUpdate = (form: EditForm) => {
    if (!editTarget) return;
    updateUser.mutate({
      id: editTarget,
      data: {
        name: form.name,
        email: form.email,
        role: form.role,
        phone: form.phone || undefined,
        isActive: form.isActive === "true",
        ...(form.password ? { password: form.password } : {}),
      },
    });
  };

  const getRoleColor = (role: string) => {
    switch (role) {
      case "admin": return "bg-violet-50 text-violet-700 ring-violet-200";
      case "sales": return "bg-blue-50 text-blue-700 ring-blue-200";
      case "finance": return "bg-emerald-50 text-emerald-700 ring-emerald-200";
      case "warehouse": return "bg-amber-50 text-amber-700 ring-amber-200";
      case "engineer": return "bg-indigo-50 text-indigo-700 ring-indigo-200";
      default: return "bg-slate-50 text-slate-700 ring-slate-200";
    }
  };

  const getRoleLabel = (role: string) =>
    role.charAt(0).toUpperCase() + role.slice(1);

  return (
    <div className="space-y-5 pb-6 sm:space-y-6">
      <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2.5">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
            <UsersIcon className="h-5 w-5" />
          </div>
          <div>
            <h1 className="font-heading text-2xl font-bold tracking-tight text-slate-900 sm:text-[1.7rem]">
              User management
            </h1>
            <p className="mt-0.5 text-sm text-slate-500">
              {users?.length ?? 0} {users?.length === 1 ? "team member" : "team members"} with system access
            </p>
          </div>
        </div>
        <button
          type="button"
          onClick={() => setShowCreateModal(true)}
          className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 sm:w-auto"
        >
          <Plus className="h-4 w-4" />
          Add user
        </button>
      </div>

      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="flex flex-col gap-4 border-b border-slate-100 bg-slate-50/60 p-4 sm:p-5 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-slate-500 shadow-sm ring-1 ring-slate-200">
              <UsersIcon className="h-4 w-4" />
            </div>
            <div>
              <h2 className="text-sm font-semibold text-slate-900">System users</h2>
              <p className="text-xs text-slate-500">Manage roles, access, and account status</p>
            </div>
          </div>
          <div className="flex w-full flex-col gap-2.5 sm:flex-row lg:w-auto">
            <div className="relative min-w-0 flex-1 sm:min-w-64">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                type="search"
                aria-label="Search users"
                placeholder="Search users..."
                className="h-10 w-full rounded-lg border border-input bg-white pl-9 pr-4 text-sm shadow-sm focus-visible:border-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/25"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <select
              aria-label="Filter users by role"
              className="h-10 w-full rounded-lg border border-input bg-white px-3 text-sm shadow-sm focus-visible:border-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/25 sm:w-44"
              value={roleFilter}
              onChange={(e) => setRoleFilter(e.target.value)}
            >
              <option value="">All roles</option>
              <option value="admin">Admin</option>
              <option value="sales">Sales</option>
              <option value="finance">Finance</option>
              <option value="warehouse">Warehouse</option>
              <option value="engineer">Engineer</option>
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-[780px] w-full table-fixed text-left">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50/30 text-[11px] uppercase tracking-[0.14em] text-slate-500">
                <th className="w-[38%] px-5 py-3.5 font-semibold sm:px-6">User details</th>
                <th className="w-[16%] px-4 py-3.5 font-semibold">Role</th>
                <th className="w-[16%] px-4 py-3.5 font-semibold">Status</th>
                <th className="w-[15%] px-4 py-3.5 font-semibold">Added</th>
                <th className="w-[15%] px-5 py-3.5 text-right font-semibold sm:px-6">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm">
              {isLoading ? (
                <TableSkeleton columns={5} />
              ) : users?.length === 0 ? (
                <EmptyTableState
                  colSpan={5}
                  title="No users found"
                  description={search || roleFilter ? "Try clearing a filter or searching for another team member." : "Add a user to start managing system access."}
                  action={search || roleFilter ? (
                    <button
                      type="button"
                      onClick={() => { setSearch(""); setRoleFilter(""); }}
                      className="text-sm font-medium text-primary hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30"
                    >
                      Clear filters
                    </button>
                  ) : undefined}
                />
              ) : (
                visibleUsers.map((user) => (
                    <tr key={user.id} className="group transition-colors hover:bg-slate-50/70">
                     <td className="px-5 py-4 sm:px-6">
                       <div className="flex min-w-0 items-center gap-3">
                         <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-slate-100 font-heading text-sm font-bold uppercase text-slate-600">
                          {user.name.charAt(0)}
                        </div>
                         <div className="min-w-0">
                           <div className="truncate font-semibold text-slate-900" title={user.name}>{user.name}</div>
                           <div className="mt-1 flex flex-col gap-1 text-xs text-slate-500">
                             <span className="flex min-w-0 items-center gap-1.5">
                               <Mail className="h-3 w-3 shrink-0 text-slate-400" /> <span className="truncate" title={user.email}>{user.email}</span>
                            </span>
                            {user.phone && (
                               <span className="flex items-center gap-1.5">
                                 <Phone className="h-3 w-3 shrink-0 text-slate-400" /> {user.phone}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-4">
                      <span className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-[11px] font-bold uppercase tracking-[0.1em] ring-1 ring-inset ${getRoleColor(user.role)}`}>
                        {user.role === "admin" && <Shield className="h-3 w-3" />}
                        {getRoleLabel(user.role)}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      {user.isActive ? (
                        <span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1.5 text-xs font-semibold text-emerald-700">
                          <CircleCheck className="h-3.5 w-3.5" />
                          Active
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1.5 text-xs font-semibold text-slate-600">
                          <CircleOff className="h-3.5 w-3.5" />
                          Inactive
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-4 text-xs text-slate-500">
                      {format(new Date(user.createdAt), "MMM d, yyyy")}
                    </td>
                    <td className="px-5 py-4 text-right sm:px-6">
                      <div className="flex justify-end gap-1.5">
                        <button
                          type="button"
                           aria-label={user.isActive ? `Deactivate ${user.name}` : `Activate ${user.name}`}
                            className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-transparent px-2 text-xs font-semibold text-slate-500 transition-colors hover:border-amber-100 hover:bg-amber-50 hover:text-amber-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30 disabled:cursor-not-allowed disabled:opacity-50"
                          title={user.isActive ? "Deactivate user" : "Activate user"}
                          disabled={togglingIds.has(user.id)}
                          onClick={() => {
                            setTogglingIds((prev) => new Set(prev).add(user.id));
                            updateUser.mutate(
                              { id: user.id, data: { isActive: !user.isActive } },
                              {
                                onSuccess: () => {
                                  toast({
                                    title: user.isActive
                                      ? `${user.name} deactivated`
                                      : `${user.name} activated`,
                                  });
                                },
                                onError: () => {
                                  toast({
                                    title: "Failed to update user status",
                                    variant: "destructive",
                                  });
                                },
                                onSettled: () => {
                                  setTogglingIds((prev) => {
                                    const next = new Set(prev);
                                    next.delete(user.id);
                                    return next;
                                  });
                                },
                              }
                            );
                          }}
                        >
                          {togglingIds.has(user.id) ? (
                            <Loader2 className="h-4 w-4 animate-spin" />
                          ) : (
                            <Power className="h-3.5 w-3.5" />
                          )}
                          <span className="hidden xl:inline">{user.isActive ? "Deactivate" : "Activate"}</span>
                        </button>
                        <button
                          type="button"
                          onClick={() => setEditTarget(user.id)}
                          className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 text-xs font-semibold text-slate-600 transition-colors hover:border-primary/30 hover:bg-primary/5 hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30"
                          aria-label={`Edit ${user.name}`}
                        >
                          Edit
                        </button>
                        {currentUser?.id !== user.id && (
                          <button
                            type="button"
                            onClick={() =>
                              setDeleteTarget({
                                id: user.id,
                                name: user.name,
                                email: user.email,
                                role: user.role,
                              })
                            }
                            className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-transparent text-slate-400 transition-colors hover:border-red-100 hover:bg-red-50 hover:text-red-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-300"
                            title="Delete user"
                            aria-label={`Delete ${user.name}`}
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        <PaginationBar
          page={page}
          pageCount={pageCount}
          total={users?.length ?? 0}
          pageSize={pageSize}
          onPageChange={setPage}
        />
      </div>

      {showCreateModal && (
        <CreateUserModal
          onClose={() => setShowCreateModal(false)}
          onCreated={() =>
            queryClient.invalidateQueries({ queryKey: getListUsersQueryKey() })
          }
        />
      )}

      {editTarget !== null && editTargetUser && (
        <EditUserModal
          userId={editTarget}
          initial={{
            name: editTargetUser.name,
            email: editTargetUser.email,
            role: editTargetUser.role as Role,
            phone: editTargetUser.phone ?? "",
            isActive: editTargetUser.isActive ? "true" : "false",
            password: "",
          }}
          onClose={() => setEditTarget(null)}
          onSubmit={handleUpdate}
          isPending={updateUser.isPending}
        />
      )}

      {deleteTarget !== null && (
        <DeleteConfirmDialog
          user={deleteTarget}
          onClose={() => setDeleteTarget(null)}
          onConfirm={() => deleteUser.mutate({ id: deleteTarget.id })}
          isPending={deleteUser.isPending}
        />
      )}
    </div>
  );
}
